name: treex_app
description: treex private cloud service client.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flare_flutter:
  provider:
  flutter_miui:
  bot_toast:
  flutter_markdown:
  carousel_slider:
  flutter_icons:
  wave:
    git:
      url: https://github.com/i-protoss/wave
  qr_flutter:
  qr_code_scanner:
  flutter_material_color_picker:
  flip_card:
  connectivity:
  shared_preferences:
  dio:
  flutter_staggered_animations:
  video_player:
  permission_handler:
  url_launcher:
  image_picker:
  path_provider:
  file_picker:
  intl:
  dio_http2_adapter:
  open_file:
  sticky_headers:
  vibration:
  web_socket_channel:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/animation/logo.flr
    - assets/imgs/logo.png
    - assets/imgs/nasa-1.webp
    - assets/imgs/nasa-2.webp
    - assets/imgs/nasa-3.webp
    - assets/imgs/nasa-4.webp
    - assets/imgs/nasa-5.webp

  fonts:
    - family: Iconfont
      fonts:
        - asset: fonts/iconfont.ttf